export const siteUrl = "https://ofivault.de";
export const telegramLicenseUsername = "rootkit_spoofer";

// Generated by src/app/opengraph-image.tsx. Pages that set their own `openGraph`
// replace the inherited image, so they must list it explicitly.
export const defaultOgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "OfiVault, encuentra tu versión de Office, Project o Visio",
};

export function getLicenseContactUrl(productTitle?: string, selectedLanguage?: string) {
  const draft = [
    productTitle ? `Hola, tengo una consulta sobre licencias para ${productTitle}.` : "Hola, tengo una consulta sobre licencias.",
    selectedLanguage ? `Idioma del instalador seleccionado: ${selectedLanguage}.` : undefined,
  ].filter(Boolean).join(" ");

  return `https://t.me/${telegramLicenseUsername}?text=${encodeURIComponent(draft)}`;
}
